// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBL3cuHsrS2-H38k_flRQuHvLrRIYKjI',
    appId: '1:552987313953:web:232dc41c4670a4a56ee060',
    messagingSenderId: '552987313953',
    projectId: 'hobbyzhubnotification',
    authDomain: 'hobbyzhubnotification.firebaseapp.com',
    storageBucket: 'hobbyzhubnotification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANNygoGhiWdpOu95OXYuukswG_QqhAsU',
    appId: '1:552987313953:android:4458a0b91d0255306ee060',
    messagingSenderId: '552987313953',
    projectId: 'hobbyzhubnotification',
    storageBucket: 'hobbyzhubnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nkdu7lQgakfl6gId9SNcrkY0suAevO4',
    appId: '1:552987313953:ios:7ecefe2594b3dbaa6ee060',
    messagingSenderId: '552987313953',
    projectId: 'hobbyzhubnotification',
    storageBucket: 'hobbyzhubnotification.appspot.com',
    iosBundleId: 'com.findstoneage.hobbyzhub.hobbyzhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nkdu7lQgakfl6gId9SNcrkY0suAevO4',
    appId: '1:552987313953:ios:2d19186ee40972716ee060',
    messagingSenderId: '552987313953',
    projectId: 'hobbyzhubnotification',
    storageBucket: 'hobbyzhubnotification.appspot.com',
    iosBundleId: 'com.findstoneage.hobbyzhub.hobbyzhub.RunnerTests',
  );
}
